---
title: "Car Noise Data Analysis"
author: "jeeyeonLIM"
output: 
  html_document :
    toc : true
---

# LARGE
# EDA


```{r}

eda_large= car_noise_complete %>%filter(type_num_final==3) 
graph_tada(input_data=eda_large)

```


# Modeling

```{r}

summary(model_large)

### 결측값 check 

    showNA(model_large, "large dataframe")
    
    
### 연속형 변수 확인
    corr_model_large= model_large %>% select_if(is.numeric) 
    library(corrplot)
    M <- cor(corr_model_large, use= "complete.obs")
    corrplot(M, method = "circle")
    

### 범주형 변수 Handling 
    
    # 변수명 확인 
    model_large %>% select_if(is.factor) %>% colnames()
    
    # 범주별 갯수 살펴보기
    input_data = model_large
        # table(input_data$brand )
        # table(input_data$model )
        # table(input_data$model_engine_compression_cqa )
    
        table(input_data$model_engine_position_cqa ) 
        table(input_data$model_engine_type_cqa )     
        table(input_data$model_transmission_type_cqa)
        table(input_data$model_engine_fuel_cqa )
        table(input_data$model_drive_cqa )          
      
      #### 아래거 이것저것 시도해보기 .... 
        table(input_data$model_body_cqa ) 
        table(input_data$make_country_cqa )
        
### Hanling 
    model_large= model_df %>%filter(type_num_final==3) %>% select(-type_num_final)
    
    model_large = model_large %>% 
      filter(model_engine_type_cqa != "boxer",
            model_transmission_type_cqa %in% c("Automatic","Manual",NA), 
                      #범주불균형-> 모형적합X
             model_engine_fuel_cqa != "Electric" # level 10개여서 제외함

             ) %>% 
      mutate(
            # model_drive_cqa = ifelse(model_drive_cqa=="Front Wheel Driv","Front Wheel Driv", 
            #                    ifelse(model_drive_cqa== "All Wheel Drive","All Wheel Drive","etc")),
             
             make_country_cqa =ifelse(make_country_cqa == "Germany","Germany",
                               ifelse(make_country_cqa == "Japan","Japan",
                               ifelse(make_country_cqa == "USA","USA","etc"))),
                               # > 100
             model_body_cqa = ifelse(model_body_cqa == "Sedan","Sedan",
                             ifelse(model_body_cqa == "SUV","SUV",
                            ifelse(model_body_cqa == "Sport Utility Vehicles", "Sport Utility Vehicles",
                            #ifelse(model_body_cqa == "Coupe", "Coupe", 
                            ifelse(is.na(model_body_cqa), NA, "etc"))))
             
             )%>%  
      select(-year,
            
             -model_engine_position_cqa,  # Middle 1개 이외에 전부 Front 형태
            #범주불균형-> 모형적합X
             -model_body_cqa,
            #-make_country_cqa,
             #-model_transmission_type_cqa,
             #-model_drive_cqa,
            
            # VIF 
            # 아래에서 상관계수 때문에 어떤 변수가 더 좋을지 살펴봄. -> AIC 기준으로 
            # 따라서 model_engine_valves_per_cyl_cqa 제외하는 게 맞다고 판단. 
             -model_engine_valves_per_cyl_cqa, # AIC: 387.74 ,rmse 9.411235 
             -model_engine_cyl_cqa, # vif= 20.0670
            # -model_engine_valves_cqa # AIC: 390.71 , rmse 9.570973
             
            
            
            -model_engine_fuel_cqa # vif > 16
            #,-model_length_mm_cqa
             ) 

### all~Modeling -> ViF check 
    summary(model_large) # data check
    model_large = model_large %>% select(-X)
                                        # ,-model_engine_fuel_cqa)
    glm_fit=  glm(dB_at_100kmh~ .,data=model_large)
    summary(glm_fit)
    
    library(car)
    vif(glm_fit) # vif 10인 값 model_length_mm_cqa 있긴 하지만 일단 모형에 넣어주기로 
    
        
### Train vs Test 

    set.seed(1)
    large_idx=sample(1:nrow(model_large), nrow(model_large)*0.7)
    model_large_train=model_large[large_idx,]
    model_large_test=model_large[-large_idx,]
    
    summary(model_large_train)
    summary(model_large_test)
    
    
### fitting 
    large_glm_fit= glm(dB_at_100kmh~ .,data=model_large_train)
    
    ss= summary(large_glm_fit)
    predict(large_glm_fit, model_large_test )
    
    rmse= sqrt ( sum( (predict(large_glm_fit, model_large_test )-model_large_test$dB_at_100kmh)^2 ,na.rm = T) )
    rmse
    
    plot( predict(large_glm_fit, model_large_test ),model_large_test$dB_at_100kmh )
    
```

```{r}

    
    showNA(model_large, "large dataframe")
    str(model_large)
        
```


    
```{r}

## Random Forest 
library(randomForest)

## 단순 평균 대체 - randomForest na.action option 
# large_rf_fit=randomForest(dB_at_100kmh~ .,
#                           data=model_large,
#                           na.action=na.roughfix, 
#                           mtry=13, importance = TRUE)
# summary(large_rf_fit)


## method1. mice 
require(mice) 
imp_cart <- mice(model_large,5, method = "cart")     # dataset을 m개 만든다. 디폴트는 5 
imp_rf <- mice(model_large,5, method = "rf")

### cart
    imp_cart
    imp_cart$imp
    densityplot(imp_cart)
    
    mice_cart = complete(imp_cart)
    mice_cart_num= mice_cart %>% select_if(is.numeric)
    #mice_cart_num=scale(mice_cart_num)
    mice_cart = mice_cart %>% select_if(is.factor) %>% cbind(mice_cart_num)


### rf 
    imp_rf
    imp_rf$imp
    densityplot(imp_rf)
    
    mice_rf = complete(imp_rf)
    mice_rf_num= mice_rf %>% select_if(is.numeric)
    #mice_rf_num=scale(mice_rf_num)
    mice_rf = mice_rf %>% select_if(is.factor) %>% cbind(mice_rf_num)
    


### Train vs Test 
# 나눌 데이터 ##################
  #model_data= mice_cart
  model_data= mice_rf
    
###################################
    set.seed(1)
    large_idx=sample(1:nrow(model_data), nrow(model_data)*0.7)
    mice_model_large_train=model_data[large_idx,]
    mice_model_large_test=model_data[-large_idx,]
    
    summary(mice_model_large_train)
    summary(mice_model_large_test)
    

### fitting 
# 적합할 데이터 ##################
  train= mice_model_large_train
  test=  mice_model_large_test
###################################
    
#### glm #########################
    fit_glm= glm(dB_at_100kmh~ .,data=train)
    ss= summary(fit_glm)
    #predict(fit_glm, test )
    
    rmse_glm= sqrt( mean((predict(fit_glm, test )-test$dB_at_100kmh)^2) )
    rmse_glm
    
    plot( predict(fit_glm, test ),test$dB_at_100kmh )
    
    fit.con <- lm(dB_at_100kmh~1,data = train)
    fit.both <- step(fit.con,scope=list(lower=fit.con,upper=fit_glm),direction = "both")
    rmse_glm_tune= sqrt( mean((predict(fit.both, test )-test$dB_at_100kmh)^2) )
    rmse_glm_tune


  ### tuning X 
    # default_glm_mod = train(
    #       form = dB_at_100kmh ~ .,
    #       data = train,
    #       trControl = trainControl(method = "cv", number = 5),
    #       method = "glm"
    #       )
    # 
    # fit_glm_tune = default_glm_mod$finalModel
    # rmse_glm_tune= sqrt( mean((predict(fit_glm_tune, test )-test$dB_at_100kmh)^2) )
    # rmse_glm_tune
    
    
#### rf#########################
    fit_rf=randomForest(dB_at_100kmh~ .,
                              data=train)
    #predict(fit_rf)
    rmse_rf= sqrt( mean((predict(fit_rf, test )-test$dB_at_100kmh)^2) )
    rmse_rf
    
    plot( predict(fit_rf, test ),test$dB_at_100kmh )
    
    
    
    ### tuning
    hyper_grid <- expand.grid(
      mtry       = seq(2, 6, by = 1),
      node_size  = seq(1, 15, by = 2),
      sampe_size = c(.55, .632, .70, .80),
      OOB_RMSE   = 0
    )
    dim(hyper_grid)
    
    for(i in 1:nrow(hyper_grid)) {
      # train model
      model <- ranger(
        formula         = dB_at_100kmh ~ ., 
        data            = train, 
        num.trees       = 500,
        mtry            = hyper_grid$mtry[i],
        min.node.size   = hyper_grid$node_size[i],
        sample.fraction = hyper_grid$sampe_size[i],
        seed            = 5
      )
      
      # add OOB error to grid
      hyper_grid$OOB_RMSE[i] <- model$prediction.error #오분류율
      #print(i)
    }
    data.frame(hyper_grid) %>% filter(OOB_RMSE == min(hyper_grid$OOB_RMSE))
    
    
    fit_rf_tune=randomForest(dB_at_100kmh~ .,data=train,
                           ntree=500,mtry=2,nodesize=5,sample_size=0.8,
                           importance=T,eta=0.11)
    
    #predict(fit_rf)
    rmse_rf_tune= sqrt( mean((predict(fit_rf_tune, test )-test$dB_at_100kmh)^2) )
    rmse_rf_tune
    
    ### Importance Plot 
    importance(fit_rf_tune)
    varImpPlot(fit_rf_tune, n.var=13)
    varImpPlot(fit_rf_tune)
    
    partialPlot(fit_rf_tune, 
                                          pred.data=train,
                                          x.var="model_height_mm_cqa")
    partialPlot(fit_rf_tune, 
                                          pred.data=train,
                                          x.var="model_doors_cqa")
    partialPlot(fit_rf_tune, 
                                          pred.data=train,
                                          x.var="model_weight_kg_cqa")
    
    
    
    
#### svr#########################
    library(e1071) 
    fit_svr <- svm(dB_at_100kmh~ .,
                              data=train, gamma=1, cost=16)
    summary(fit_svr)
    rmse_svr= sqrt( mean((predict(fit_svr, test )-test$dB_at_100kmh)^2) )
    rmse_svr
    
    plot( predict(fit_svr, test ),test$dB_at_100kmh )

    
    ### tuning
    tuneResult <- tune(svm, dB_at_100kmh ~ ., data = train,
                        ranges = list(epsilon = seq(0.3,1,0.1), cost = 2^(2:9)))
    print(tuneResult) # epsilon0.7   cost 4
    plot(tuneResult)
    fit_svr_tune <- tuneResult$best.model
    
    rmse_svr_tune= sqrt( mean((predict(fit_svr_tune, test )-test$dB_at_100kmh)^2) )
    rmse_svr_tune
    
    plot( predict(fit_svr_tune, test ),test$dB_at_100kmh )
    
#### xgboost#########################
    library(xgboost)
    X.train <- model.matrix(dB_at_100kmh ~ . -1, train) 
    X.test <- model.matrix(dB_at_100kmh ~ . -1, test)
    train.xgb <- xgb.DMatrix(X.train, label=train$dB_at_100kmh)
    test.xgb <- xgb.DMatrix(X.test, label=test$dB_at_100kmh)
    
    watchlist <- list(train=train.xgb, test=test.xgb)
    
    xgb <- xgb.train(data=train.xgb, label=train$dB_at_100kmh, 
                     max_depth = 1000, eta = 0.1, nthread = 3,nrounds = 100, #1.776072
                     
                     watchlist=watchlist)
    
    xgb.pred.train = predict(xgb, train.xgb)
    xgb.pred.test = predict(xgb, test.xgb)
    
    rmse_xgb= sqrt( mean((xgb.pred.test-test$dB_at_100kmh)^2) )
    rmse_xgb 
    
    
    ### tuning
    hyper_grid <- expand.grid(
      
      eta       = seq(0.1, 0.5, by = 0.1),
      nthread  = seq(3, 8, by = 1),

      nrounds = seq(65, 70, by = 1),
      OOB_RMSE   = 0
      
      # eta       = seq(0.1, 0.7, by = 0.1),
      # nthread  = seq(3, 6, by = 1),
      # 
      # nrounds = seq(50, 55, by = 1),
      # OOB_RMSE   = 0
      
      #0.3       3      55 3.034455
    )
    
    
    for(i in 1:nrow(hyper_grid)) {
      # train model
      model <- xgb.train(data=train.xgb, 
                         label=train$dB_at_100kmh, 
                         max_depth = 500, 
                         eta = hyper_grid$eta[i], 
                         nthread = hyper_grid$nthread[i], 
                         nrounds = hyper_grid$nrounds[i]#, 
                         
                         #watchlist=watchlist
                         )
    
      # add OOB error to grid
      hyper_grid$OOB_RMSE[i] <- sqrt( mean((predict(model, test.xgb)-test$dB_at_100kmh)^2) )
      #print(i)
    }
    
    data.frame(hyper_grid) %>% filter(OOB_RMSE == min(hyper_grid$OOB_RMSE))
    
    
    ### FINAL...ㅠㅠ 
    
    ## cart
    # xgb <- xgb.train(data=train.xgb, label=train$dB_at_100kmh,
    #                  max_depth = 1000, eta =  0.2, nthread = 3,nrounds = 50, #1.776072
    #                  watchlist=watchlist)
    
    ##rf
    xgb <- xgb.train(data=train.xgb, label=train$dB_at_100kmh,
                     #max_depth = 1000, eta = 0.2, nthread = 3,nrounds = 50, #1.776072
                     max_depth = 1000, eta = 0.1, nthread = 3,nrounds = 1000, #1.776072
                     watchlist=watchlist)
    
    xgb.pred.train = predict(xgb, train.xgb)
    xgb.pred.test = predict(xgb, test.xgb)
    
    rmse_xgb_tune= sqrt( mean((xgb.pred.test-test$dB_at_100kmh)^2) )
    rmse_xgb_tune # 3.2482 보다 
    
    
    ### Importance Plot 
    mat <- xgb.importance (model = xgb)
    xgb.plot.importance (importance_matrix = mat) 
        
    
### RESULT #########################
    
    data.frame(rmse_glm = rmse_glm, 
               rmse_rf= rmse_rf,
               rmse_rf_tune= rmse_rf_tune,
               rmse_svr= rmse_svr,
               rmse_svr_tune= rmse_svr_tune,
               rmse_xgb= rmse_xgb,
               rmse_xgb_tune= rmse_xgb_tune)
    
    ppt_final = 
      data.frame(rmse_glm = round(rmse_glm,4), 
               rmse_rf_tune= round(rmse_rf_tune,4),
               rmse_svr_tune= round(rmse_svr_tune,4),
               rmse_xgb_tune= round(rmse_xgb_tune,4))
    ppt_final
    
    
    
    
######### 
    final_model=
    data.frame(
        pred_y = predict(fit_rf_tune, test ),
        real_y = test$dB_at_100kmh
        )  
    ggplot(final_model, aes(pred_y, real_y)) +
          geom_point() + 
          stat_smooth(method = lm) + theme_bw()
        

```








# 3.최적값 찾기

```{r}

ss$coefficients[,1]

a=data.frame(ss$coefficients[,1])
View(a)
#write.csv(a,"lllarge.csv")

# model_engine_cc_cqa
# model_engine_type_cqaV
# model_drive_cqaFour Wheel Drive
# model_drive_cqaFront Wheel Driv
# model_drive_cqaRear Wheel Drive
# model_transmission_type_cqaManual
# model_seats_cqa
# model_doors_cqa
# model_weight_kg_cqa
# model_length_mm_cqa
# model_width_mm_cqa
# model_height_mm_cqa
# model_wheelbase_mm_cqa
# model_lkm_mixed_cqa
# model_fuel_cap_l_cqa
# model_engine_valves_cqa
# model_engine_power_kw_cqa
# model_engine_torque_kgm_cqa
# make_country_cqaGermany
# make_country_cqaJapan
# make_country_cqaUSA


###### 시작 ~!
# 목적식
z <- c(-0.00181514	,
      # 0.302061328	,
      # -0.686217862	,
      # -0.239499896	,
      # -0.736835665	,
      # 1.930748685	,
      -0.17974442	,
      -0.890429786	,
      -0.004865599	,
      -0.000873439	,
      0.009109787	,
      0.005307314	,
      -0.000404884	,
      0.052550073	,
      -0.023905013	,
      -0.07126974	,
      0.025283551	,
      0.039923144	
      # 0.420209073	,
      # 0.34089064	,
      # 0.764330968	
      )


A <- matrix(c(1,0,0,0,0,0,0,0,0,0,0,0,0,
              1,0,0,0,0,0,0,0,0,0,0,0,0,
              0,1,0,0,0,0,0,0,0,0,0,0,0,
              0,1,0,0,0,0,0,0,0,0,0,0,0,
              0,0,1,0,0,0,0,0,0,0,0,0,0,
              0,0,1,0,0,0,0,0,0,0,0,0,0,
              0,0,0,1,0,0,0,0,0,0,0,0,0,
              0,0,0,1,0,0,0,0,0,0,0,0,0,
              0,0,0,0,1,0,0,0,0,0,0,0,0,
              0,0,0,0,1,0,0,0,0,0,0,0,0,
              0,0,0,0,0,1,0,0,0,0,0,0,0,
              0,0,0,0,0,1,0,0,0,0,0,0,0,
              0,0,0,0,0,0,1,0,0,0,0,0,0,
              0,0,0,0,0,0,1,0,0,0,0,0,0,
              0,0,0,0,0,0,0,1,0,0,0,0,0,
              0,0,0,0,0,0,0,1,0,0,0,0,0,
              0,0,0,0,0,0,0,0,1,0,0,0,0,
              0,0,0,0,0,0,0,0,1,0,0,0,0,
              0,0,0,0,0,0,0,0,0,1,0,0,0,
              0,0,0,0,0,0,0,0,0,1,0,0,0,
              0,0,0,0,0,0,0,0,0,0,1,0,0,
              0,0,0,0,0,0,0,0,0,0,1,0,0,
              0,0,0,0,0,0,0,0,0,0,0,1,0,
              0,0,0,0,0,0,0,0,0,0,0,1,0,
              0,0,0,0,0,0,0,0,0,0,0,0,1,
              0,0,0,0,0,0,0,0,0,0,0,0,1
              ), 
            nrow=26, byrow=TRUE)

# 제약식의 우변
B <- c(min(model_large[,2],na.rm=T),max(model_large[,2],na.rm=T), 
       min(model_large[,3],na.rm=T),max(model_large[,3],na.rm=T), 

       min(model_large[,6],na.rm=T),max(model_large[,6],na.rm=T), 
       min(model_large[,7],na.rm=T),max(model_large[,7],na.rm=T), 
       min(model_large[,8],na.rm=T),max(model_large[,8],na.rm=T), 
       min(model_large[,9],na.rm=T),max(model_large[,9],na.rm=T), 
       min(model_large[,10],na.rm=T),max(model_large[,10],na.rm=T), 
       min(model_large[,11],na.rm=T),max(model_large[,11],na.rm=T), 
       min(model_large[,12],na.rm=T),max(model_large[,12],na.rm=T), 
       min(model_large[,13],na.rm=T),max(model_large[,13],na.rm=T), 
       min(model_large[,14],na.rm=T),max(model_large[,14],na.rm=T), 
       min(model_large[,15],na.rm=T),max(model_large[,15],na.rm=T), 
       min(model_large[,16],na.rm=T),max(model_large[,16],na.rm=T), 
       min(model_large[,17],na.rm=T),max(model_large[,17],na.rm=T)
       
       )

# 제약식의 부등호
dir  <- c(">", "<=", 
          ">", "<=", 
          ">", "<=", 
          ">", "<=", 
          ">", "<=", 
          
          ">", "<=", 
          ">", "<=", 
          ">", "<=", 
          ">", "<=", 
          ">", "<=", 
          
          ">", "<=", 
          ">", "<=", 
          ">", "<=", 
          ">", "<=", 
          ">", "<="
          
          )

# 최적해
opt <-  lp(direction="min",
           objective.in = z,
           const.mat = A,
           const.dir = dir,
           const.rhs = B,
           all.int = T)

# 결과
opt

# 결정변수
opt$solution

# 가장 가까운 값을 가지는 차량 찾기 
###  V
### Front Wheel Driv
### Automatic
### USA

  ## 값 setting
  
    
    model_engine_type_cqaV  =1
    
    model_drive_cqaFour_Wheel_Drive  =0
    model_drive_cqaFront_Wheel_Driv  =1
    model_drive_cqaRear_Wheel_Drive   =0
    
    model_transmission_type_cqaManual =0
    
    make_country_cqaGermany  =0
    make_country_cqaJapan    =0
    make_country_cqaUSA      =1

  ## 계산 
    y= ss$coefficients[,1][1] +
      (ss$coefficients[,1][2] *opt$solution[1] )+
      
      (ss$coefficients[,1][3] *model_engine_type_cqaV )+
      (ss$coefficients[,1][4] *model_drive_cqaFour_Wheel_Drive )+ 
      (ss$coefficients[,1][5] *model_drive_cqaFront_Wheel_Driv)+
      (ss$coefficients[,1][6] *model_drive_cqaRear_Wheel_Drive )+
      (ss$coefficients[,1][7] *model_transmission_type_cqaManual )+
      
      (ss$coefficients[,1][8] *opt$solution[2] )+
      (ss$coefficients[,1][9] *opt$solution[3] )+
      (ss$coefficients[,1][10] *opt$solution[4] )+
      (ss$coefficients[,1][11] *opt$solution[5] )+
      (ss$coefficients[,1][12] *opt$solution[6] )+
      (ss$coefficients[,1][13] *opt$solution[7] )+
      (ss$coefficients[,1][14] *opt$solution[8] )+
      (ss$coefficients[,1][15] *opt$solution[9] )+
      (ss$coefficients[,1][16] *opt$solution[10] )+
      (ss$coefficients[,1][17] *opt$solution[11] )+
      (ss$coefficients[,1][18] *opt$solution[12] )+
      (ss$coefficients[,1][19] *opt$solution[13] )+
      
      (ss$coefficients[,1][20] *make_country_cqaGermany )+
      (ss$coefficients[,1][21] *make_country_cqaJapan )+
      (ss$coefficients[,1][22] *make_country_cqaUSA )
    
      
    print(y)
    
    
    
    USA=model_large %>%
      filter( make_country_cqa == "USA") %>% 
      
      mutate( dist=
        (model_engine_cc_cqa -opt$solution[1])^2+
          
        (model_seats_cqa -opt$solution[2])^2+
        (model_doors_cqa -opt$solution[3])^2+
        (model_weight_kg_cqa -opt$solution[4])^2+
        (model_length_mm_cqa -opt$solution[5])^2+
        (model_width_mm_cqa-opt$solution[6])^2+
        (model_height_mm_cqa-opt$solution[7])^2+
        (model_wheelbase_mm_cqa-opt$solution[8])^2+
        (model_lkm_mixed_cqa-opt$solution[9])^2+
        (model_fuel_cap_l_cqa-opt$solution[10])^2+
        (model_engine_valves_cqa-opt$solution[11])^2+
        (model_engine_power_kw_cqa-opt$solution[12])^2+
        (model_engine_torque_kgm_cqa-opt$solution[13])^2
        
        ) %>% 
      filter(model_engine_type_cqa=="V",
             model_drive_cqa == "Front Wheel Driv",
             model_transmission_type_cqa == "Automatic",
             make_country_cqa == "USA"
             ) %>% 
      arrange(dist)
    View(USA)
    
    
    car_noise_complete %>% filter(type_num_final ==3,
                                  dB_at_100kmh==65.6,
                                  model_engine_cc_cqa==3496
                                  ) 
    
    # 563  Ford  Flex 3.5 V6 2009
    
### V
### Front Wheel Driv
### Automatic
### USA
car_noise %>% filter(X==563) %>% select(
  
   model_engine_cc_cqa,



model_seats_cqa,
model_doors_cqa
,
model_weight_kg_cqa,
model_length_mm_cqa,
model_width_mm_cqa,
model_height_mm_cqa,
model_wheelbase_mm_cqa,
model_lkm_mixed_cqa,
model_fuel_cap_l_cqa,
model_engine_valves_cqa,
model_engine_power_kw_cqa,
model_engine_torque_kgm_cqa
  
  
  
  
  
)



```







